export enum UrlsProperties {

  //BASE_URLS = 'http://172.16.120.250:8081',
  //BASE_URLS = 'http://192.168.0.15:8081',
  BASE_URLS = 'http://localhost:8081',

  PATH_LOGIN = BASE_URLS + '/autenticacion/iniciarSesion',
  PATH_CHANCE_PASS = BASE_URLS + '/autenticacion/cambiarPass',
  PATH_CLOSE_LOGIN = BASE_URLS + '/autenticacion/cerrarSesion',

  PATH_DELETE_USER = BASE_URLS + '/administrador/eliminarFuncionario/',
  PATH_LIST_USERS = BASE_URLS + '/administrador/listaDeUsuarios',
  PATH_LIST_CARGOS = BASE_URLS + '/administrador/listarCargos',
  PATH_LIST_ROLES = BASE_URLS + '/administrador/listarRoles',
  PATH_LIST_UNIDADES = BASE_URLS + '/administrador/listarUnidades',
  PATH_CREATE_USER = BASE_URLS + '/administrador/crearUsuario',
  PATH_EDIT_USER = BASE_URLS + '/administrador/editarUsuario',

  PATH_LIST_SOLIC = BASE_URLS + '/solicitante/verSolicitudesPendientes',
  PATH_AUTORIZ_SOLI = BASE_URLS + '/solicitante/verSolicitudesAutorizadas',
  PATH_CREATE_SOLICITUD = BASE_URLS + '/solicitante/solicitarFotocopiar',
  PATH_SOLICITUD_PDF = BASE_URLS + '/solicitante/exportSolicitudDPF/',
  PATH_ORDENFOTO_PDF = BASE_URLS + '/solicitante/exportOrdenDeSolicitudDPF/',
  PATH_COMUINTERNA_PDF = BASE_URLS + '/solicitante/exportComunicacionInternaDPF/',
  PATH_INFORSOLI_PDF = BASE_URLS + '/solicitante/exportInformeSolicitudDPF/',
  PATH_FINALIZADAS_SOLI = BASE_URLS + '/solicitante/verSolicitudesFinalizadas',
  PATH_ELIMINAR_SOLIC = BASE_URLS + '/solicitante/eliminarSolicitudById/',
  PATH_LIST_TAM = BASE_URLS + '/solicitante/listarTamano',
  PATH_LIST_ANVER = BASE_URLS + '/solicitante/listarAnversoReverso',
  PATH_LIST_COLOR = BASE_URLS + '/solicitante/listarColor',
  SUSCRIBE_SOLICITANTE = BASE_URLS + '/solicitante/notificacion',
  PATH_DOCU_RETIRO = BASE_URLS + '/solicitante/verDocumentosRetiro/',
  PATH_REGIS_RETIRODOCU = BASE_URLS + '/solicitante/registrarDocumentosRetiro',
  PATH_IS_INFORME = BASE_URLS + '/solicitante/isInforme/',

  PATH_NOTA_PDF = BASE_URLS + '/responsable/exportNotaPedidoDPF/',
  PATH_REPORTE_PDF = BASE_URLS + '/responsable/exportReporteDPF',
  PATH_LIST_SOLIPENDIENTE = BASE_URLS + '/responsable/verSolicitudesPendientes',
  PATH_LIST_SOLIAPRO = BASE_URLS + '/responsable/verSolicitudesAprobadas',
  PATH_LIST_SOLIFINALI = BASE_URLS + '/responsable/verSolicitudesFinalizadas',
  PATH_SOLI_BYID = BASE_URLS + '/responsable/verSolicitudesPendientesByIdSolicitud',
  PATH_SOLI_AUTORIBYID = BASE_URLS + '/responsable/verSolicitudesAutoriByIdSolicitud',
  PATH_SOLI_FINALIBYID = BASE_URLS + '/responsable/verSolicitudesFinaliByIdSolicitud',
  PATH_DETALLE_SOLI = BASE_URLS + '/responsable/verDetalleDeSolicitud/',
  PATH_AUTORIZAR_SOLI = BASE_URLS + '/responsable/autorizarSolicitud',
  PATH_RECHAZAR_SOLI = BASE_URLS + '/responsable/rechazarSolicitud',
  PATH_AUTORI_SOLI = BASE_URLS + '/responsable/verAutorizacionSolicitud/',
  PATH_FINALIZAR_SOLI = BASE_URLS + '/responsable/finalizarSolicitud',
  SUSCRIBE_RESPONSABLE = BASE_URLS + '/responsable/notificacion'
}
